apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer-k8s.fullname" . }}
  labels:
    {{- include "homer-k8s.labels" . | nindent 4 }}
    {{- if .Values.service.additionalLabels }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "homer-k8s.selectorLabels" . | nindent 4 }}
