apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: bananaops/homer-k8s
      ko: 
        main: ./cmd/
deploy:
  helm:
    releases:
      - name: homer-k8s
        chartPath: helm/homer-k8s
        namespace: homer
        createNamespace: true
        #artifactOverrides:
        #  image: jplanckeel/homer-k8s
        #imageStrategy:
        #  helm: {}
