---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - homer.bananaops.io
  resources:
  - homerservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homer.bananaops.io
  resources:
  - homerservices/finalizers
  verbs:
  - update
- apiGroups:
  - homer.bananaops.io
  resources:
  - homerservices/status
  verbs:
  - get
  - patch
  - update
